## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
notifications:
  email: false
matrix:
  include:
    - os: linux
      julia: 1.0
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 1.1
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: 1.2
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 1.0
      env: TESTCMD="julia"
    - os: osx
      julia: 1.1
      env: TESTCMD="julia"
    - os: osx
      julia: 1.2
      env: TESTCMD="julia"

script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - $TESTCMD -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'
    
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("JuliaKara")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("JuliaKara")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - $TESTCMD -e 'import Pkg; include(joinpath("docs", "make.jl"))'
